stages:
  - build
  - release
  - test
  - notify

build_a:
 stage: build
 script:
    - echo "Building a..."
include:
  - template: Security/SAST.gitlab-ci.yml
  - local: 'backend/.gitlab-ci-backend.yml'
  - local: 'frontend/.gitlab-ci-frontend.yml'