stages:
  - build
  - test
  - release
  - notify
  - module-pipelines
  - deploy
  
include:
  - template: Security/SAST.gitlab-ci.yml
  - local: 'backend/.gitlab-ci-backend.yml'
  - local: 'frontend/.gitlab-ci-frontend.yml'

variables:
  VERSION: 0.0.${CI_PIPELINE_ID}
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository 
    - .npm/

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "frontend.gitlab-ci.yml"
    strategy: depend 
  only:
    changes: 
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "backend.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${DEV_USER}@${DEV_HOST} "curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} -o ~/sausage-store-${VERSION}.jar ${NEXUS_REPO_URL}/${NEXUS_REPO_BACKEND_NAME}/com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar"