cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

variables:
   VERSION: 1.0.${CI_PIPELINE_ID}
   MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
   JAVA_OPTS: -XX:MaxRAMPercentage=90 

stages:
   - build
   - release

build:
   stage: build
   script:
      - cd backend
      - >
         mvn package
         -Dversion.application=${VERSION}
         -Dmaven.repo.local=${MAVEN_REPO_PATH}
   rules: 
      - changes:
           - backend/**/*

