stages:
  - build

build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/**/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
  
  telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/**/*
  script:
    - curl <отправка вашего сообщения>
  needs:
    - build-backend-code-job