apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: docker-config-secret
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-ext-028-45/sausagestore/sausage-store/backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config
          volumeMounts:
            - name: postgres-cert
              mountPath: /app/postgres.crt
              subPath: postgres.crt
            - name: mongo-cert
              mountPath: /app/root.crt
              subPath: root.crt
      volumes:
        - name: postgres-cert
          secret:
            secretName: postgres-cert
        - name: mongo-cert
          secret:
            secretName: mongo-cert