spring.datasource.url=jdbc:postgresql://rc1b-9l4s7gem400cgpdj.mdb.yandexcloud.net:6432/std-ext-028-45
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=std-ext-028-45
spring.datasource.password=Testusr1234
spring.jpa.hibernate.ddl-auto=none  
spring.flyway.enabled=true
spring.data.mongodb.uri=mongodb://user:pass@host:port/db?tls=true
