apiVersion: v1
kind: Secret
metadata:
  name: backend-report-secret
type: Opaque
stringData:
  DB: "mongodb://std-ext-028-62:Testusr1234@rc1b-aoneasa5cshk6o30.mdb.yandexcloud.net:27018/std-ext-028-62?replicaSet=rs01&tls=true&tlsCAFile=/app/root.crt"