
build-frontend-code-job:
  stage: build  
  only:
    changes:
    - frontend/**/*
  script:        
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend 
      
  telegram-notification-backend:
  stage: notify
  only:
    changes:
      - frontend/**/*
  script:
    - |
      curl -X POST \
        -H 'Content-Type: application/json' \
        -d "{\"chat_id\": \"-1003263328596\", \"text\": \"Frontend собран. Артефакты: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/download?job=$CI_JOB_NAME\"}" \
        https://api.telegram.org/bot5933756043:AAG6cdxMAdOtN3-NQ9sfS4CdpGuS8ilASwA/sendMessage
  needs:
    - build-backend-code-job